// Datastruktur for stillinger
const stillinger = ["Rektor", "Dekan", "Vaktmester", "Professor", "Lektor"];

// Datastruktur for ansatte på hiof
const ansatte = [
  {
    fornavn: "Lars-Petter",
    etternavn: "Jelsness-Jørgensen",
    stilling: stillinger[0], // Bruker index for å gi riktig stilling
    kontor: "M-408(1) og A3-001(1)",
    epost: "lars.p.jelsness-jorgensen@hiof.no",
    kursansvar: [], // Tomme array fordi de ikke har ansvar for noen kurs
  },
  {
    fornavn: "Randi",
    etternavn: "Magnus Sommerfelt",
    stilling: stillinger[1],
    kontor: "A3-004(2) og M-404",
    epost: "randi.sommerfelt@hiof.no",
    kursansvar: [],
  },
  {
    fornavn: "Ann-Chatrin",
    etternavn: "Linqvist Leonardsen",
    stilling: stillinger[1],
    kontor: "M-405",
    epost: "ann.c.leonardsen@hiof.no",
    kursansvar: [],
  },
  {
    fornavn: "Per",
    etternavn: "Johansen",
    stilling: stillinger[2],
    kontor: "V001",
    epost: "per.johansen@hiof.no",
    kursansvar: [],
  },
  {
    fornavn: "Khalid",
    etternavn: "Ali",
    stilling: stillinger[2],
    kontor: "V002",
    epost: "khalid.ali@hiof.no",
    kursansvar: [],
  },
  {
    fornavn: "Siri",
    etternavn: "Hansen",
    stilling: stillinger[2],
    kontor: "V003",
    epost: "siri.hansen@hiof.no",
    kursansvar: [],
  },
  {
    fornavn: "Hilde",
    etternavn: "Wågsås Afdal",
    stilling: stillinger[3],
    kontor: "E1-054(2)",
    epost: "hilde.afdal@hiof.no",
    kursansvar: [
      "Grunnskolelærerutdanning for trinn 5 - 10",
      "Master i mangfold og integrering",
      "PhD kurs: Education in the Digital Socety",
    ],
  },
  {
    fornavn: "Cecilia",
    etternavn: "Alvstad",
    stilling: stillinger[3],
    kontor: "A3-106(2)",
    epost: "cecilia.alvstad@hiof.no",
    kursansvar: [
      "Språklig Variasjon",
      "Spansk språkvitenskap I: Ord",
      "Spansk språkvitenskap III: Tekst",
    ],
  },
  {
    fornavn: "Mona",
    etternavn: "Jerndahl Fineide",
    stilling: stillinger[3],
    kontor: "A-336",
    epost: "mona.j.fineide@hiof.no",
    kursansvar: ["Samfunnsvitenskap"],
  },
  {
    fornavn: "Anders",
    etternavn: "Dechsling",
    stilling: stillinger[3],
    kontor: "F1-083",
    epost: "anders.dechsling@hiof.no",
    kursansvar: [
      "Sosiale og emosjonelle vansker",
      "Rådgiving, veiledning og innovasjon i spesialpedagogisk virksomhet",
    ],
  },
  {
    fornavn: "Lilliana",
    etternavn: "Andrea Del Busso",
    stilling: stillinger[3],
    kontor: "A-303",
    epost: "lilliana.a.busso@hiof.no",
    kursansvar: [
      "Health, Quality of Life and Digitalisation",
      "Research Methods",
    ],
  },
  {
    fornavn: "Tore",
    etternavn: "Marius Akerbæk",
    stilling: stillinger[4],
    kontor: "D1-016",
    epost: "tore.m.akerbak@hiof.no",
    kursansvar: [
      "Utvikling av interaktive nettsteder",
      "Grafisk design",
      "Kommunikasjonsdesign",
      "Innføring i programmering",
    ],
  },
  {
    fornavn: "Hege",
    etternavn: "Hedlund Andersen",
    stilling: stillinger[4],
    kontor: "A-201",
    epost: "hege.h.andersen@hiof.no",
    kursansvar: [
      "Bachelorstudium i barnevern",
      "Barn i offentlig omsorg - barnevernfaglig oppfølgingsarbeid",
      "Innføring i barnevern for andre studieretninger",
    ],
  },
  {
    fornavn: "Petter André",
    etternavn: "Høntorp Arvesen",
    stilling: stillinger[4],
    kontor: "A-335",
    epost: "petter.a.arvesen@hiof.no",
    kursansvar: [
      "Tverrfaglig videreutdanning i psykososialt arbeid med barn og unge",
      "Bachelorstudium i barnevern",
    ],
  },
  {
    fornavn: "Fred Rune",
    etternavn: "Bjordal",
    stilling: stillinger[4],
    kontor: "E1-054(5)",
    epost: "fred.r.bjordal@hiof.no",
    kursansvar: [
      "Grunnskolelærerutdanning for trinn 5-10",
      "Grunnskolelærerutdanning for trinn 1-7",
    ],
  },
  {
    fornavn: "Therese",
    etternavn: "Westreng Borgland",
    stilling: stillinger[4],
    kontor: "C2-038",
    epost: "therese.w.borgland@hiof.no",
    kursansvar: [
      "Barns utvikling, lek og læring 2",
      "Småbarnspedagogikk fordypning",
    ],
  },
  {
    fornavn: "Rolf-Einar",
    etternavn: "Grini Bryggfjell",
    stilling: stillinger[4],
    kontor: "S-407",
    epost: "rolf.e.bryggfjell@hiof.no",
    kursansvar: ["Matematikk for Tress og Y-veien, del II"],
  },
  {
    fornavn: "Siri Ellen",
    etternavn: "Adelaide Brynhildsen",
    stilling: stillinger[4],
    kontor: "N-321",
    epost: "siri.e.brynhildsen@hiof.no",
    kursansvar: [
      "Bachelor i sykepleie",
      "Sykepleie- helse, sykdom og lidelse I",
    ],
  },
  {
    fornavn: "Veronica",
    etternavn: "Eidesgaard",
    stilling: stillinger[4],
    kontor: "A-230(2)",
    epost: "veronica.eidesgaard@hiof.no",
    kursansvar: ["Faglig ledelse, samhandling og pasientsikkerhet"],
  },
  {
    fornavn: "Silje Marie",
    etternavn: "Engen",
    stilling: stillinger[4],
    kontor: "N-226",
    epost: "silje.m.engen@hiof.no",
    kursansvar: ["Psykisk helsearbeid", "Grunnleggende sykepleie"],
  },
  {
    fornavn: "Marius",
    etternavn: "Geitle",
    stilling: stillinger[4],
    kontor: "D1-012",
    epost: "marius.geitle@hiof.no",
    kursansvar: ["Big Data: Lagring og Bearbeiding - emneansvarlig"],
  },
];
